apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: fevermap
  name: fevermap-api
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: fevermap-api:latest
  runPolicy: Serial
  source:
    contextDir: api
    git:
      ref: openshift
      uri: https://gitlab.com/fevermap/fevermap.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.openshift
      from:
        kind: ImageStreamTag
        name: debian:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
