apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: fevermap
    app.kubernetes.io/component: fevermap
    app.kubernetes.io/instance: fevermap
    app.kubernetes.io/part-of: fevermap
  name: fevermap
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: fevermap
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: fevermap
    spec:
      containers:
      - image: fevermap@latest
        imagePullPolicy: Always
        name: fevermap
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - fevermap
      from:
        kind: ImageStreamTag
        name: fevermap:latest
        namespace: fevermap-3
    type: ImageChange
