apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx-runtime
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: centos/nginx-112-centos7:latest
    name: latest
    referencePolicy:
      type: Source
