apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8-s2i-web-app
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: nodeshift/ubi8-s2i-web-app:10.x
    name: latest
    referencePolicy:
      type: Source
