apiVersion: v1
data:
  database-name: ZmV2ZXJtYXA=
  database-password: ZmV2ZXJwYXNz
  database-root-password: cm9vdHBhc3M=
  database-user: ZmV2ZXJtYXA=
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: mariadb-ephemeral-template
  name: fevermap-db
type: Opaque
