---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "fevermap",
      "namespace": "fevermap-staging", "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: fevermap
  name: fevermap-release
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ocp/staging/pipelines/fevermap-release
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
    - generic:
        secretReference:
          name: gitlab-webhook
        allowEnv: true
      type: Generic
