---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    env: staging
  name: fevermap-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: fevermap-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    images:
      - as: null
        from:
          kind: ImageStreamTag
          name: fevermap-app-compile:latest
        paths:
          - destinationDir: .
            sourcePath: /opt/app-root/output/.
    type: Image
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/rhel8/nginx-116
      incremental: false
      pullSecret:
        name: registry-redhat-io-secret
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
