apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    env: staging
  name: fevermap-app-compile
  selfLink: /apis/build.openshift.io/v1/namespaces/fevermap-staging/buildconfigs/fevermap-app-compile
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: fevermap-app-compile:latest
  postCommit: {}
  resources:
    limits:
      memory: 2Gi
  runPolicy: Serial
  source:
    contextDir: app
    git:
      uri: https://gitlab.com/fevermap/fevermap.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: NPM_BUILD
        value: webpack --mode production --env.NODE_ENV=production
      - name: OUTPUT_DIR
        value: dist
      from:
        kind: ImageStreamTag
        name: ubi8-s2i-web-app:latest
    type: Source
  successfulBuildsHistoryLimit: 5
