apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: fevermap-db
  creationTimestamp: null
  generation: 1
  labels:
    app: fevermap
    app.kubernetes.io/component: fevermap-api
    app.kubernetes.io/instance: fevermap-api
    app.kubernetes.io/part-of: fevermap
    env: staging
  name: fevermap-api
  selfLink: /apis/apps.openshift.io/v1/namespaces/fevermap-staging/deploymentconfigs/fevermap-api
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    app: fevermap-api
    deploymentconfig: fevermap-api
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fevermap-api
        deploymentconfig: fevermap-api
    spec:
      containers:
      - env:
        - name: FEVERMAP_API_DATABASE_URI
          valueFrom:
            secretKeyRef:
              key: database-uri
              name: fevermap-api-db
        - name: FLASK_ENV
          value: kube
        - name: APP_SCRIPT
          value: entrypoint.sh
        - name: APPDIR
          value: /opt/app-root/src
        - name: UWSGIPLUGINLINE
        image: fevermap-staging/fevermap-api:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: fevermap-api
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src/entrypoint.sh
          name: uwsgi-starter
          readOnly: true
          subPath: entrypoint.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 360
          name: fevermap-api-uwsgi-starter
        name: uwsgi-starter
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - fevermap-api
      from:
        kind: ImageStreamTag
        name: fevermap-api:latest
        namespace: fevermap-staging
    type: ImageChange
  - type: ConfigChange
