---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    env: staging
  name: fevermap-app-compile
spec:
  lookupPolicy:
    local: false
