apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    env: staging
  name: ubi8-s2i-web-app
  selfLink: /apis/image.openshift.io/v1/namespaces/fevermap-staging/imagestreams/ubi8-s2i-web-app
spec:
  lookupPolicy:
    local: false
