apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    env: staging
  name: fevermap-api
  selfLink: /apis/image.openshift.io/v1/namespaces/fevermap-staging/imagestreams/fevermap-api
spec:
  lookupPolicy:
    local: false
