---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: certbot-ocp
  name: certbot-letsencrypt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-encrypted
  volumeName: pvc-50d119e2-85f2-11ea-bf7a-0645a759894e
