---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri:
      mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}
  creationTimestamp: null
  labels:
    env: staging
    template: mariadb-ephemeral-template
  name: fevermap-db
  selfLink: /api/v1/namespaces/fevermap-staging/services/fevermap-db
spec:
  ports:
    - name: mariadb
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    name: fevermap-db
  sessionAffinity: None
  type: ClusterIP
