apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  labels:
    app: fevermap
    app.kubernetes.io/component: front
    app.kubernetes.io/instance: fevermap-front
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: fevermap
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-version: "1.12"
    application: fevermap
  name: fevermap-front
  selfLink: /apis/autoscaling/v1/namespaces/fevermap-prod/horizontalpodautoscalers/fevermap-front
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: fevermap-front
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
