apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    controller-uid: 05ce38b1-73de-11ea-bf7a-0645a759894e
    job-name: db-backup-1585720800
    parent: db-backup
  name: db-backup-1585720800
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: db-backup
    uid: 6262ce50-73dd-11ea-bf7a-0645a759894e
  selfLink: /apis/batch/v1/namespaces/fevermap-prod/jobs/db-backup-1585720800
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 05ce38b1-73de-11ea-bf7a-0645a759894e
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 05ce38b1-73de-11ea-bf7a-0645a759894e
        job-name: db-backup-1585720800
        parent: db-backup
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: fevermap-db
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: fevermap-db
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: fevermap-db
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: aws-db-backup
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET
              name: aws-db-backup
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              key: AWS_S3_BUCKET
              name: aws-db-backup
        - name: AWS_S3_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_S3_REGION
              name: aws-db-backup
        image: quay.io/fevermap/db-backup-job:latest
        imagePullPolicy: Always
        name: db-backup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
