---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger:
      "LimitRanger plugin set: cpu request for container
      certbot-ocp; cpu limit for container certbot-ocp"
    openshift.io/scc: restricted
  creationTimestamp: null
  labels:
    app: certbot-ocp
    name: certbot-ocp
  name: certbot-ocp
spec:
  activeDeadlineSeconds: 3600
  containers:
    - env:
        - name: ROUTE_LABEL
          value: letsencrypt-me=true
        - name: EMAIL
          value: tahonen@redhat.com
        - name: CERTBOT_EXTRA_OPTS
      image: quay.io/fevermap/certbot-ocp:0.9.3
      imagePullPolicy: Always
      name: certbot-ocp
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 512Mi
        requests:
          cpu: 30m
          memory: 409Mi
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - NET_RAW
            - SETGID
            - SETUID
        runAsUser: 1123720000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /etc/letsencrypt
          name: letsencrypt
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: certbot-token-96hkv
          readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: certbot-dockercfg-ddwkq
  nodeName: ip-172-31-55-74.eu-west-1.compute.internal
  nodeSelector:
    type: compute
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1123720000
    seLinuxOptions:
      level: s0:c352,c84
  serviceAccount: certbot
  serviceAccountName: certbot
  terminationGracePeriodSeconds: 10
  tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
  volumes:
    - name: letsencrypt
      persistentVolumeClaim:
        claimName: certbot-letsencrypt
    - name: certbot-token-96hkv
      secret:
        defaultMode: 420
        secretName: certbot-token-96hkv
