---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: Fevermap Production
    openshift.io/plan-type: OpenshiftOnlinePaid
    openshift.io/requester: tahonen@redhat.com
    openshift.io/sa.scc.mcs: s0:c352,c84
    openshift.io/sa.scc.supplemental-groups: 1123720000/10000
    openshift.io/sa.scc.uid-range: 1123720000/10000
  name: fevermap-prod
spec:
  finalizers:
    - kubernetes
