apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: fevermap-mysql-runtime
    application: fevermap
    template: fevermap-mysql-persistent
  name: fevermap-mariadb-storage
  selfLink: /api/v1/namespaces/fevermap-prod/persistentvolumeclaims/fevermap-mariadb-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-encrypted
  volumeName: pvc-e002f680-7276-11ea-bf7a-0645a759894e
status: {}
