---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: certbot-ocp
  name: certbot-ocp
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: certbot-ocp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
