---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: fevermap
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: fevermap
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: fevermap
    application: fevermap
  name: fevermap-api
spec:
  ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    deploymentconfig: fevermap-api
  sessionAffinity: None
  type: ClusterIP
