---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: fevermap-mysql-runtime
    application: fevermap
    template: fevermap-mysql-persistent
  name: fevermap-front
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    deploymentconfig: fevermap-front
  sessionAffinity: None
  type: ClusterIP
