---

- name: redhat.io pull secret
  tags: secrets
  when: api_build or app_build or push_api_build
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: v1
        data:
          .dockerconfigjson: "{{ redhat_io_pull_token }}"
        kind: Secret
        metadata:
          labels:
            app: "{{ app }}"
            env: staging
          name: registry-redhat-io-secret
        type: kubernetes.io/dockerconfigjson

- name: Gitlab webhook secret
  tags: secrets
  when: api_build or app_build or push_api_build
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: v1
        data:
          WebHookSecretKey:
            "{{ api_gitlab_webhook_secret_key | string | b64encode }}"
        kind: Secret
        metadata:
          labels:
            env: staging
            app: "{{ app }}"
          name: "{{ app }}-gitlab-webhook"
        type: Opaque

- name: Quay.io push secret
  tags: secrets
  when: api_build or app_build or push_api_build
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: v1
        data:
          password: "{{ quay_push_passwd | string | b64encode }}"
          username: "{{ quay_push_user | string | b64encode }}"
        kind: Secret
        metadata:
          creationTimestamp: null
          labels:
            credential.sync.jenkins.openshift.io: "true"
            env: staging
          name: quay-push-secret
          selfLink: /api/v1/namespaces/fevermap-staging/secrets/quay-push-secret
        type: Opaque

- name: Slack webhook secret
  tags: secrets
  when: (api_build or app_build or push_api_build) and slack_webhook_url is defined
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: v1
        data:
          password: "{{ slack_webhook_url | string | b64encode }}"
          username: "openshift"
        kind: Secret
        metadata:
          creationTimestamp: null
          labels:
            credential.sync.jenkins.openshift.io: "true"
            env: staging
          name: slack-webhook-secret
        type: Opaque

- name: Database secret
  tags:
    - secrets
    - db
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: v1
        stringData:
          database-name: "{{ db_name }}"
          database-password: "{{ db_password }}"
          database-root-password: "{{ db_root_password }}"
          database-user: "{{ db_user }}"
          database-uri:
            "mysql://{{ db_user }}:{{ db_password }}@{{ app }}-db/{{ db_name }}\
            ?charset=utf8mb4"
        kind: Secret
        metadata:
          labels:
            app: "{{ app }}"
          annotations:
            template.openshift.io/expose-database_name:
              "{.data['database-name']}"
            template.openshift.io/expose-password:
              "{.data['database-password']}"
            template.openshift.io/expose-root_password:
              "{.data['database-root-password']}"
            template.openshift.io/expose-username:
              "{.data['database-user']}"
            template.openshift.io/expose-database_uri:
              "{.data['database-uri']}"
          name: "{{ app }}-db"
        type: Opaque
