---

- name: Define persistent storage for database
  tags: db
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          labels:
            app: "{{ app }}"
          finalizers:
            - kubernetes.io/pvc-protection
          name: "{{ app }}-mariadb-storage"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "{{ db_size }}"

- name: Define deployment config for database
  tags: db
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        metadata:
          annotations:
            template.alpha.openshift.io/wait-for-ready: "true"
          creationTimestamp: null
          generation: 1
          labels:
            app.kubernetes.io/component: database
            app.kubernetes.io/instance: "{{ app }}-db"
            app.kubernetes.io/name: mariadb
            app.kubernetes.io/part-of: "{{ app }}"
            app.openshift.io/runtime: mariadb
            app: "{{ app }}"
          name: "{{ app }}-db"
        spec:
          replicas: 1
          revisionHistoryLimit: 5
          selector:
            deploymentconfig: "{{ app }}-db"
          strategy:
            activeDeadlineSeconds: 21600
            recreateParams:
              timeoutSeconds: 600
            type: Recreate
          template:
            metadata:
              creationTimestamp: null
              name: "{{ app }}-db"
              labels:
                deploymentconfig: "{{ app }}-db"
            spec:
              containers:
                - env:
                    - name: MYSQL_USER
                      valueFrom:
                        secretKeyRef:
                          key: database-user
                          name: "{{ app }}-db"
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: database-password
                          name: "{{ app }}-db"
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: database-root-password
                          name: "{{ app }}-db"
                    - name: MYSQL_DATABASE
                      valueFrom:
                        secretKeyRef:
                          key: database-name
                          name: "{{ app }}-db"
                  image: openshift/mariadb@latest
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    failureThreshold: 3
                    initialDelaySeconds: 30
                    periodSeconds: 10
                    successThreshold: 1
                    tcpSocket:
                      port: 3306
                    timeoutSeconds: 1
                  name: mariadb
                  ports:
                    - containerPort: 3306
                      protocol: TCP
                  readinessProbe:
                    exec:
                      command:
                        - /bin/sh
                        - -i
                        - -c
                        - >-
                          MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1
                          -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'
                    failureThreshold: 3
                    initialDelaySeconds: 5
                    periodSeconds: 10
                    successThreshold: 1
                    timeoutSeconds: 1
                  resources:
                    limits:
                      memory: "{{ db_memory_limit }}"
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /var/lib/mysql/data
                      name: "{{ app }}-data"
              dnsPolicy: ClusterFirst
              restartPolicy: Always
              schedulerName: default-scheduler
              terminationGracePeriodSeconds: 30
              volumes:
                - name: "{{ app }}-data"
                  persistentVolumeClaim:
                    claimName: "{{ app }}-mariadb-storage"
          test: false
          triggers:
            - imageChangeParams:
                automatic: true
                containerNames:
                  - mariadb
                from:
                  kind: ImageStreamTag
                  name: "{{ db_image }}"
                  namespace: openshift
              type: ImageChange
            - type: ConfigChange

- name: Define service for database
  tags: db
  k8s:
    state: "{{ state }}"
    definition:
      - apiVersion: v1
        kind: Service
        metadata:
          annotations:
            template.openshift.io/expose-uri: >-
              mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}
          labels:
            app.kubernetes.io/component: "{{ app }}-db"
            app.kubernetes.io/instance: "{{ app }}-db"
            app.kubernetes.io/name: "{{ app }}-db"
            app.kubernetes.io/part-of: "{{ app }}"
            app: "{{ app }}"
          name: "{{ app }}-db"
        spec:
          ports:
            - name: mariadb
              port: 3306
              protocol: TCP
              targetPort: 3306
          selector:
            deploymentconfig: "{{ app }}-db"
          sessionAffinity: None
          type: ClusterIP
