---
# NOTE! This is only for starting a development environment easily.
# Do not run in production with this setup.

version: "2"

services:

  api:
    image: "fevermap/api:latest"
    build: .
    links:
      - database
    volumes:
      - ".:/app:rw"
    command: "'nc -vz database 3306'\n"
    ports:
      - 9000:9000

  # Database container is for development only, thus default credentials are ok
  # Access MariaDB console with:
  #   docker exec -it fevermap_database_1 mysql -prootpass fevermap
  database:
    image: "ypcs/mariadb:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=fevermap
      - MYSQL_USER=fevermap
      - MYSQL_PASSWORD=feverpass
    volumes:
      - "database:/var/lib/mysql:rw"

volumes:
  database: ~
